### ISSUE TITLE
O cálculo da menhera-chan não acerta quando o número for 0

### ISSUE THREAD

**Issue by luan0ap** [FelypeGanzert/Menhera-chan_Quiz#1]
Ela não acerta o número quando é 0, mesmo perguntando se o número for menor que 1. Acredito o número 1 seja um valor padrão nas variáveis que ela usa para calcular a resposta

**Comment by FelypeGanzert** [comment]
Muito obrigado por ter notado isso. Fiz uma pequena alteração (gambiarra) para ele estar considerando de -1 até 1000 ao invés de 0 até 1000. Acredito que agora o problema tenha sido resolvido.
